### ISSUE TITLE
Timeout; Operation too slow

### ISSUE THREAD

**Issue by ds82** [Enalean/ansible-tuleap#14]
I'm getting the following error on the Tuleap Task:

```
TASK [Enalean.Tuleap : Install Tuleap]
...
Timeout on https://tuleap.net/pub/tuleap/yum/rhel/7/
stable/x86_64/tuleap-12.1-1.el7.noarch.rpm: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')\nTrying other mirror.\n\n\nGPG key retrieval failed: [Errno 12] Timeout on https://tuleap.net/pub/tuleap/yum/gpg.key: (28, 'Operation too slow. Less than 1000 bytes/sec
transferred the last 30 seconds')
...
```

Is this really a problem with the mirror?
Can I force a specific mirror somehow?

I attached the complete log.

[tuleap-error.log](https://github.com/Enalean/ansible-tuleap/files/5421877/tuleap-error.log)

**Comment by LeSuisse** [comment]
Hi,

I suggest to retry, it looks like it was a temporary failure.

**Comment by LeSuisse** [comment]
Hello,

We confirm there is an issue with this specific endpoint/repository. The current version of playbook does not use it anymore so the issue should be resolved.
