### ISSUE TITLE
Cannot access to trackers after updating from Tuleap 8.9 to 8.12

### ISSUE THREAD

**Issue by pletessier** [Enalean/ansible-tuleap#2]
Hi,

I tried to update from Tuleap 8.9 to 8.12 by changing the "tuleap_packages_state" variable to "latest".
It was OK until I noticed I wasn't able anymore to access to the tracker plugin. 

The solution seems to be to add "tuleap-plugin-tracker" to the list of "tuleap_packages".

Pierre

**Comment by tomcottier** [comment]
Hi,

How did you install Tuleap? With the Ansible plugin or using the standard way?

**Comment by pletessier** [comment]
With the ansible plugin.

**Comment by tomcottier** [comment]
Ok I'll have a look at it. Updating the tuleap_packages list is the good way to solve this problem.

**Comment by pletessier** [comment]
I solved some new occuring problems by reading and applying the commands described here : http://tuleap-documentation.readthedocs.org/en/latest/installation-guide/update.html

The ansible role seems to miss the "forgeupgrade" command. Thanks for the role anyway !
