### ISSUE TITLE
Iptables configuration should be in prerequisites

### ISSUE THREAD

**Issue by pfreund** [Enalean/ansible-tuleap#6]
On AWS cloud, Centos start with rules in iptables. These rules makes Tuleap inaccessible.

dependencies.yml should check iptables like it does for selinux.

**Comment by tcottier-enalean** [comment]
What would you suggest as a test? You can't presume the iptables configuration that will be deployed.

Plus tuleap works well with iptables as opposed to selinux that breaks it.
